### ISSUE TITLE
Automate docs creation?

### ISSUE THREAD

**Issue by davisdude** [excessive/cpml#11]
Do you think we should include a bat file to automate docs for users?
For instance, what I used looks like this:

``` batch
@echo off
lua "C:\Program Files (x86)\Lua\ldoc\ldoc.lua" %*
```

**Comment by shakesoda** [comment]
I don't think we should include a bat script, but that they should be generated automatically when pushes happen (maybe we can have travis do it)

**Comment by TannerRogalsky** [comment]
Having Travis push to `gh-pages` is not too bad and is reasonably secure. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
