### ISSUE TITLE
Refactor modules for a more consistent API, new in-place APIs to reduce GC pressure.

### ISSUE THREAD

**Issue by shakesoda** [excessive/cpml#12]
Making an issue for this. Work is happening in the refactor branch.

* [x] update intersect (8b136798d26de87a2af90786632cc17853790696)
* [x] update vec2 (870a3c5129c3e1a0fd8330d4de3a48f23796dd3b)
* [x] update vec3 (1531bf4abb027bbba57ff512d1930aec63db3c0d)
* [x] update quat (85655e65af11f352c35abc9f788e5beb570340a3)
* [x] update mat4
* [ ] add mat3
* [x] add point functions into vec2 (namely the polar coordinate conversions)
* [x] update docs for vec2 (c5d02e0683c9bf0e480559b2e14bc5077bc77f60)
* [x] update docs for vec3 (57704e9dba57f98063edd427519655d8a7bf87e0)
* [x] update docs for quat (85655e65af11f352c35abc9f788e5beb570340a3)
* [ ] update docs for mat4
* [x] new tests for vec2
* [x] new tests for vec3
* [x] new tests for quat
* [ ] new tests for mat3
* [x] new tests for mat4
* [ ] ensure everything works on PUC Lua as well as LuaJIT.

**Comment by karai17** [comment]
Updated mat4 and added tests for vec2, vec3

**Comment by karai17** [comment]
Added tests for quat

**Comment by karai17** [comment]
Added a bunch of tests for mat4. Now I am going to commit suicide. Bye.

**Comment by karai17** [comment]
I decided to commit more code instead.

**Comment by shakesoda** [comment]
Merged. Hopefully no major regressions.
