### ISSUE TITLE
Spherical coordinate system

### ISSUE THREAD

**Issue by davisdude** [excessive/cpml#13]
Spherical coordinates are basically 3D polar coordinates. I was reading up on them, and apparently there are two common ways to do them, the "physics" way and the "math" way. Is there a certain way anybody likes better than the other?

"Physics" way:
![Physics way](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/3D_Spherical.svg/240px-3D_Spherical.svg.png)
"Math" way
![Math way](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/3D_Spherical_2.svg/240px-3D_Spherical_2.svg.png)

**Comment by shakesoda** [comment]
I'd go for the math way unless someone has any compelling reason otherwise.

**Comment by karai17** [comment]
They look pretty darn similar to me, but as @shakesoda said, the mathy way is probably most idea for a math library.

**Comment by davisdude** [comment]
The difference is whether the second coordinate goes off of the x-axis or the z-axis. 

I agree with @karai17, since it is a math library after all.
