### ISSUE TITLE
nil passed to isvector should return false

### ISSUE THREAD

**Issue by Trebgarta** [excessive/cpml#16]
When a nil is passed, it errors, "attempt to index v (a nil value)".

**Comment by davisdude** [comment]
Do you think it should error or just return false?

**Comment by Trebgarta** [comment]
Well, a nil is not a vec3, so it should return false. Erring should be the choice of the caller.

**Comment by shakesoda** [comment]
it was this way intentionally, but in hindsight it makes more sense that it'd nil check by itself. I'll take care of it.

**Comment by davisdude** [comment]
Don't know if you're planning on doing it this way or not, but I think it would be easiest to just add a simple check for truthiness at the beginning. I.e

```lua
function isvector(v)
    return v and -- ...
end
```

**Comment by davisdude** [comment]
@shakesoda I went ahead and fixed it via [commit 112](https://github.com/excessive/cpml/commit/ee4ec8ba2a96e76593814f714cc43a2127b994f1)

**Comment by shakesoda** [comment]
thanks!
