### ISSUE TITLE
Release on LuaRocks

### ISSUE THREAD

**Issue by pranas** [excessive/cpml#18]
Hey guys

Did you consider releasing ``cpml`` on LuaRocks? Do you have anything against it?

https://github.com/keplerproject/luarocks

**Comment by shakesoda** [comment]
I'm in favor, I just don't know how to work LuaRocks.

**Comment by pranas** [comment]
You can follow the guide [here](https://github.com/keplerproject/luarocks/wiki/Creating-a-rock). Once you create rockspec file the following releases seem like a breeze.

**Comment by Alloyed** [comment]
https://github.com/Alloyed/loverocks-repo/blob/master/cpml-scm-1.rockspec
I stopped doing 3d stuff so I don't think this is up to date but hey~
test it by stuffing the rockspec in the project dir and doing
```
luarocks make --tree=rocks/
```

**Comment by shakesoda** [comment]
http://luarocks.org/modules/shakesoda/cpml

**Comment by pranas** [comment]
Yay, that's great, thanks! It would be even better if you released non-dev version (1.0 maybe?). So people don't need to specify the custom Luarocks source server.
