### ISSUE TITLE
mat4.look_at doesn't translate vertices properly

### ISSUE THREAD

**Issue by krassell** [excessive/cpml#40]
When using mat4.look_at to generate camera transformation matrix the resulting matrix doesn't translate vertices into the camera space properly, resulting in all vertex coordinates being negated. I.e. vertex with coordinates (10, 10, 10) will become (-10,-10,-10) from camera's standpoint.
This is caused by elements 13, 14 and 15 of said matrix being set to 0. Replacing these values with negative dot products (As can be seen here: https://en.wikipedia.org/wiki/Graphics_pipeline#Camera_Transformation ) apparently solves the issue.

**Comment by shakesoda** [comment]
looks like i forgot to backport this fix from the haxe version, thanks for bringing it up

**Comment by mcclure** [comment]
I think this is addressed by #47, at least, the test now passes

**Comment by mcclure** [comment]
Can we close this? Can anyone construct an example that fails with version 1.0.0?

**Comment by monolifed** [comment]
There are a few minor issues:
Parameter `look_at` has the same name as the function even though it is referred to as `center` in the documentation.
Parameter `a` is not used anywhere

**Comment by shakesoda** [comment]
this has been fixed for a while, although there's still the bug in the function signature
